'use client';

import { useMemo, useState } from 'react';

import { Plus, X } from 'lucide-react';

import { useCreateVariant, useUpdateVariant, Variant } from '@/hooks/useVariantQueries';
import { Button } from '@/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/ui/dialog';
import { Input } from '@/ui/input';
import { Label } from '@/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/ui/select';

type VariantDialogProps = {
  variant: Variant | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
};

type ValueForm = {
  id?: number; // For existing values when editing
  value: string;
  slug: string;
  status: 'active' | 'inactive';
};

const INITIAL_FORM = {
  name: '',
  slug: '',
  status: 'active' as 'active' | 'inactive',
};

const INITIAL_VALUE: ValueForm = {
  value: '',
  slug: '',
  status: 'active',
};

// Internal component to handle form state and logic.
// Separating this allows us to use the `key` prop in the parent to reset state automatically.
function VariantForm({
  variant,
  onSuccess,
  onCancel,
}: {
  variant: Variant | null;
  open: boolean;
  onSuccess: () => void;
  onCancel: () => void;
}) {
  const isEdit = !!variant;
  const createMutation = useCreateVariant();
  const updateMutation = useUpdateVariant();

  const initialData = useMemo(
    () =>
      variant
        ? {
            name: variant.name,
            slug: variant.slug,
            status: variant.status || 'active',
          }
        : INITIAL_FORM,
    [variant],
  );

  const [formData, setFormData] = useState(initialData);
  const [values, setValues] = useState<ValueForm[]>(
    variant?.values?.map(v => ({
      id: v.id,
      value: v.value,
      slug: v.slug,
      status: v.status || 'active',
    })) || [{ ...INITIAL_VALUE }],
  );

  // Effect to reset form removed. State reset handled by key prop in parent.

  // Auto-generate variant slug from name
  const handleNameChange = (name: string) => {
    const autoSlug = name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');

    setFormData(prev => {
      const prevAutoSlug = prev.name
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-|-$/g, '');
      const isSlugAutoGenerated = prev.slug === prevAutoSlug || prev.slug === '';

      return {
        ...prev,
        name,
        slug: isSlugAutoGenerated ? autoSlug : prev.slug,
      };
    });
  };

  // Handle value input change
  const handleValueChange = (index: number, field: 'value' | 'slug' | 'status', val: string) => {
    setValues(prev => {
      const updated = [...prev];

      if (!updated[index]) return prev; // Safety check

      if (field === 'value') {
        // Auto-generate slug from value
        const autoSlug = val
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, '-')
          .replace(/^-|-$/g, '');
        const prevAutoSlug = updated[index].value
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, '-')
          .replace(/^-|-$/g, '');
        const isSlugAutoGenerated =
          updated[index].slug === prevAutoSlug || updated[index].slug === '';

        updated[index] = {
          ...updated[index],
          value: val,
          slug: isSlugAutoGenerated ? autoSlug : updated[index].slug,
        };
      } else if (field === 'slug') {
        // Sanitize slug input
        const sanitized = val
          .toLowerCase()
          .replace(/\s+/g, '-')
          .replace(/[^a-z0-9-]/g, '');
        updated[index] = { ...updated[index], slug: sanitized };
      } else {
        updated[index] = { ...updated[index], [field]: val as 'active' | 'inactive' };
      }

      return updated;
    });
  };

  // Add new value field
  const addValue = () => {
    setValues(prev => [...prev, { ...INITIAL_VALUE }]);
  };

  // Remove value field
  const removeValue = (index: number) => {
    if (values.length > 1) {
      setValues(prev => prev.filter((_, i) => i !== index));
    }
  };

  const isDirty = useMemo(() => {
    const isFormDirty = JSON.stringify(formData) !== JSON.stringify(initialData);

    const currentValues = values.map(v => ({
      id: v.id,
      value: v.value,
      slug: v.slug,
      status: v.status,
    }));

    const initialValues = (variant?.values || []).map(v => ({
      id: v.id,
      value: v.value,
      slug: v.slug,
      status: v.status,
    }));

    if (!variant) {
      return isFormDirty || JSON.stringify(values) !== JSON.stringify([{ ...INITIAL_VALUE }]);
    }

    return isFormDirty || JSON.stringify(currentValues) !== JSON.stringify(initialValues);
  }, [formData, initialData, values, variant]);

  const isFormValid = () => {
    if (!formData.name.trim() || !formData.slug.trim()) return false;
    if (values.length === 0) return false;
    return values.every(v => v.value.trim() && v.slug.trim());
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!isFormValid()) {
      return;
    }

    try {
      if (isEdit && variant) {
        await updateMutation.mutateAsync({
          id: variant.id,
          data: {
            ...formData,
            values: values.map(({ id, value, slug, status }) => ({ id, value, slug, status })),
          },
        });
      } else {
        await createMutation.mutateAsync({
          ...formData,
          values: values.map(({ value, slug, status }) => ({ value, slug, status })),
        });
      }
      onSuccess();
    } catch {
      // Error handling is done in the hook
    }
  };

  const isLoading = createMutation.isPending || updateMutation.isPending;

  return (
    <form onSubmit={handleSubmit}>
      <DialogHeader>
        <DialogTitle>{isEdit ? 'Edit Variant' : 'Add New Variant'}</DialogTitle>
        <DialogDescription>
          {isEdit
            ? 'Update variant details and manage its values.'
            : 'Create a new variant with multiple values (e.g., Color: Red, Blue, Green).'}
        </DialogDescription>
      </DialogHeader>

      <div className="space-y-6 py-4">
        {/* Variant Details */}
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="name">Variant Name*</Label>
            <Input
              id="name"
              placeholder="e.g. Color, Size, Material"
              value={formData.name}
              onChange={e => handleNameChange(e.target.value)}
              required
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="slug">Slug*</Label>
            <Input
              id="slug"
              placeholder="e.g. color"
              value={formData.slug}
              onChange={e => {
                const sanitized = e.target.value
                  .toLowerCase()
                  .replace(/\s+/g, '-')
                  .replace(/[^a-z0-9-]/g, '');
                setFormData({ ...formData, slug: sanitized });
              }}
              required
            />
            <p className="text-muted-foreground text-xs">
              URL-friendly identifier (lowercase, no spaces)
            </p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="status">Status*</Label>
            <Select
              value={formData.status}
              onValueChange={value =>
                setFormData({ ...formData, status: value as 'active' | 'inactive' })
              }
            >
              <SelectTrigger id="status">
                <SelectValue placeholder="Select status" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="active">Active</SelectItem>
                <SelectItem value="inactive">Inactive</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>

        {/* Variant Values */}
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <Label>Variant Values* (minimum 1)</Label>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={addValue}
              leftIcon={<Plus className="h-4 w-4" />}
            >
              Add Value
            </Button>
          </div>

          <div className="border-muted space-y-3 rounded-lg border p-4">
            {values.map((val, index) => (
              <div
                key={index}
                className="bg-muted/30 flex gap-2 rounded-md p-3"
              >
                <div className="flex-1 space-y-2">
                  <Input
                    placeholder="Value (e.g. Red)"
                    value={val.value}
                    onChange={e => handleValueChange(index, 'value', e.target.value)}
                    required
                  />
                  <Input
                    placeholder="Slug (e.g. red)"
                    value={val.slug}
                    onChange={e => handleValueChange(index, 'slug', e.target.value)}
                    required
                  />
                </div>
                <div className="w-32">
                  <Select
                    value={val.status}
                    onValueChange={value => handleValueChange(index, 'status', value)}
                  >
                    <SelectTrigger className="h-10">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="active">Active</SelectItem>
                      <SelectItem value="inactive">Inactive</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                {values.length > 1 && (
                  <Button
                    type="button"
                    variant="ghost"
                    justify="center"
                    size="icon"
                    onClick={() => removeValue(index)}
                    className="text-destructive hover:bg-destructive/10 h-10 w-10 shrink-0"
                  >
                    <X className="h-4 w-4" />
                  </Button>
                )}
              </div>
            ))}
          </div>
        </div>
      </div>

      <DialogFooter>
        <Button
          type="button"
          variant="outline"
          onClick={onCancel}
          disabled={isLoading}
        >
          Cancel
        </Button>
        <Button
          type="submit"
          variant="solid"
          isLoading={isLoading}
          disabled={isLoading || !isFormValid() || (isEdit && !isDirty)}
        >
          {isEdit ? 'Update Variant' : 'Add Variant'}
        </Button>
      </DialogFooter>
    </form>
  );
}

export function VariantDialog({ variant, open, onOpenChange }: VariantDialogProps) {
  return (
    <Dialog
      open={open}
      onOpenChange={onOpenChange}
    >
      <DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto">
        <VariantForm
          key={variant?.id ?? 'create'}
          variant={variant}
          open={open}
          onSuccess={() => onOpenChange(false)}
          onCancel={() => onOpenChange(false)}
        />
      </DialogContent>
    </Dialog>
  );
}
