-- Seed default permissions
INSERT INTO permissions (slug, description, resourceGroup) VALUES
  ('dashboard.read', 'View dashboard', 'Dashboard'),
  ('analytics.read', 'View analytics', 'Analytics'),
  ('orders.read', 'View orders', 'Sales'),
  ('orders.manage', 'Manage orders', 'Sales'),
  ('invoices.read', 'View invoices', 'Sales'),
  ('products.read', 'View products', 'Catalog'),
  ('products.manage', 'Manage products', 'Catalog'),
  ('categories.read', 'View categories', 'Catalog'),
  ('categories.manage', 'Manage categories', 'Catalog'),
  ('brands.read', 'View brands', 'Catalog'),
  ('brands.manage', 'Manage brands', 'Catalog'),
  ('variants.read', 'View variants', 'Catalog'),
  ('variants.manage', 'Manage variants', 'Catalog'),
  ('collections.read', 'View collections', 'Catalog'),
  ('collections.manage', 'Manage collections', 'Catalog'),
  ('reviews.read', 'View reviews', 'Catalog'),
  ('grades.read', 'View grades', 'Catalog'),
  ('grades.manage', 'Manage grades', 'Catalog'),
  ('warranties.read', 'View warranties', 'Catalog'),
  ('warranties.manage', 'Manage warranties', 'Catalog'),
  ('barcodes.read', 'View barcodes', 'Catalog'),
  ('vendors.read', 'View vendors', 'Procurement'),
  ('vendors.manage', 'Manage vendors', 'Procurement'),
  ('purchase_orders.read', 'View purchase orders', 'Procurement'),
  ('purchase_orders.manage', 'Manage purchase orders', 'Procurement'),
  ('goods_receipts.read', 'View goods receipts', 'Procurement'),
  ('goods_receipts.manage', 'Manage goods receipts', 'Procurement'),
  ('stock.read', 'View stock', 'Inventory'),
  ('stock_movements.read', 'View stock movements', 'Inventory'),
  ('stock_movements.manage', 'Manage stock movements', 'Inventory'),
  ('locations.read', 'View locations', 'Inventory'),
  ('locations.manage', 'Manage locations', 'Inventory'),
  ('customers.read', 'View customers', 'CRM'),
  ('customers.manage', 'Manage customers', 'CRM'),
  ('support_tickets.read', 'View support tickets', 'Support'),
  ('discounts.read', 'View discounts', 'Marketing'),
  ('pages.read', 'View pages', 'Storefront'),
  ('theme.read', 'View theme', 'Storefront'),
  ('cookie_banner.read', 'View cookie banner', 'Storefront'),
  ('social_media.read', 'View social media', 'Storefront'),
  ('settings.read', 'View settings', 'Settings'),
  ('settings.manage', 'Manage settings', 'Settings'),
  ('rbac.read', 'View roles and permissions', 'System'),
  ('rbac.manage', 'Manage roles and permissions', 'System'),
  ('users.read', 'View users', 'System'),
  ('users.manage', 'Manage users', 'System')
ON DUPLICATE KEY UPDATE
  description = VALUES(description),
  resourceGroup = VALUES(resourceGroup);
