'use client';

import { useMemo, useState } from 'react';

import { toast } from 'sonner';

import {
  Category,
  useCreateCategory,
  useGetAllCategories,
  useUpdateCategory,
} from '@/hooks/useCategoryQueries';
import { Button } from '@/ui/button';
import { GeneralCombobox } from '@/ui/combobox';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/ui/dialog';
import { Input } from '@/ui/input';
import { Label } from '@/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/ui/select';
import SortableImageUpload from '@/ui/sortable-upload';
import { Textarea } from '@/ui/textarea';

type CategoryDialogProps = {
  category: Category | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
};

const INITIAL_FORM = {
  name: '',
  slug: '',
  description: '',
  imageUrl: null as string | null,
  parentId: null as number | null,
  status: 'active' as 'active' | 'inactive',
};

export function CategoryDialog({ category, open, onOpenChange }: CategoryDialogProps) {
  const isEdit = !!category;
  const createMutation = useCreateCategory();
  const updateMutation = useUpdateCategory();

  // Fetch potential parent categories (only roots)
  const { data: categoriesData } = useGetAllCategories(false, false);

  const potentialParents = useMemo(() => {
    if (!categoriesData?.items) return [];
    // If editing, exclude self from potential parents to avoid cycles
    const roots = categoriesData.items.filter(c => (c.parentId ?? null) === null);
    if (isEdit && category) {
      return roots.filter(c => c.id !== category.id);
    }
    return roots;
  }, [categoriesData, isEdit, category]);

  const initialData = useMemo(
    () =>
      category
        ? {
            name: category.name,
            slug: category.slug,
            description: category.description || '',
            imageUrl: category.imageUrl || null,
            parentId: category.parentId,
            status: category.status || 'active',
          }
        : INITIAL_FORM,
    [category],
  );

  const [formData, setFormData] = useState(initialData);

  // Auto-generate slug from name (only if slug hasn't been manually edited)
  const handleNameChange = (name: string) => {
    const autoSlug = name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');

    setFormData(prev => {
      // Check if current slug was auto-generated from previous name
      const prevAutoSlug = prev.name
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-|-$/g, '');
      const isSlugAutoGenerated = prev.slug === prevAutoSlug || prev.slug === '';

      return {
        ...prev,
        name,
        slug: isSlugAutoGenerated ? autoSlug : prev.slug,
      };
    });
  };

  const isDirty = JSON.stringify(formData) !== JSON.stringify(initialData);
  const isRootCategory = (formData.parentId ?? null) === null;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    const name = (formData.name ?? '').trim();
    const slug = (formData.slug ?? '').trim();
    if (!name) {
      toast.error('Category name is required');
      return;
    }
    if (!slug) {
      toast.error('Slug is required');
      return;
    }

    const siblings = categoriesData?.items ?? [];
    const parentId = formData.parentId ?? null;
    const parentCategory =
      parentId !== null ? (siblings.find(c => c.id === parentId) ?? null) : null;
    const hasDuplicateName = siblings.some(
      c =>
        c.id !== category?.id &&
        (c.parentId ?? null) === parentId &&
        c.name.trim().toLowerCase() === name.toLowerCase(),
    );
    if (hasDuplicateName) {
      toast.error('A category with this name already exists under the selected parent.');
      return;
    }
    if (parentCategory) {
      if (parentCategory.name.trim().toLowerCase() === name.toLowerCase()) {
        toast.error('A subcategory cannot share the same name as its parent.');
        return;
      }
    }

    const hasDuplicateSlug = siblings.some(
      c =>
        c.id !== category?.id &&
        (c.parentId ?? null) === parentId &&
        c.slug.trim().toLowerCase() === slug.toLowerCase(),
    );
    if (hasDuplicateSlug) {
      toast.error('A category with this slug already exists under the selected parent.');
      return;
    }
    if (parentCategory) {
      if (parentCategory.slug.trim().toLowerCase() === slug.toLowerCase()) {
        toast.error('A subcategory cannot share the same slug as its parent.');
        return;
      }
    }

    const payload = {
      ...formData,
      name,
      slug,
      imageUrl: parentId === null ? (formData.imageUrl ?? null) : null,
      parentId,
    };

    try {
      if (isEdit && category) {
        await updateMutation.mutateAsync({ id: category.id, data: payload });
      } else {
        await createMutation.mutateAsync(payload);
      }
      onOpenChange(false);
    } catch {
      // Error handling is done in the hook
    }
  };

  const isLoading = createMutation.isPending || updateMutation.isPending;

  return (
    <Dialog
      open={open}
      onOpenChange={onOpenChange}
    >
      <DialogContent className="max-w-md">
        <form onSubmit={handleSubmit}>
          <DialogHeader>
            <DialogTitle>{isEdit ? 'Edit Category' : 'Add New Category'}</DialogTitle>
            <DialogDescription>
              {isEdit ? 'Update category details below.' : 'Add a new category to the system.'}
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label>Category Image (Parent Categories Only)</Label>
              {isRootCategory ? (
                <SortableImageUpload
                  maxFiles={1}
                  maxSize={2 * 1024 * 1024}
                  accept="image/png,image/jpeg,image/webp"
                  showInstructions={false}
                  value={formData.imageUrl ? [formData.imageUrl] : []}
                  onChange={urls => setFormData(prev => ({ ...prev, imageUrl: urls[0] ?? null }))}
                />
              ) : (
                <div className="text-muted-foreground bg-muted/30 rounded-md border p-3 text-sm">
                  Images are available only for parent categories.
                </div>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="name">Category Name*</Label>
              <Input
                id="name"
                placeholder="e.g. Electronics"
                value={formData.name}
                onChange={e => handleNameChange(e.target.value)}
                required
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="slug">Slug*</Label>
              <Input
                id="slug"
                placeholder="e.g. electronics"
                value={formData.slug}
                onChange={e => {
                  const sanitized = e.target.value
                    .toLowerCase()
                    .replace(/\s+/g, '-')
                    .replace(/[^a-z0-9-]/g, '');
                  setFormData({ ...formData, slug: sanitized });
                }}
                required
              />
              <p className="text-muted-foreground text-xs">
                URL-friendly identifier (lowercase, no spaces)
              </p>
            </div>

            <div className="space-y-2">
              <Label htmlFor="parentId">Parent Category</Label>
              <GeneralCombobox
                id="parentId"
                placeholder="Select parent category (optional)"
                data={[
                  { value: 'none', label: 'None (Top Level)' },
                  ...potentialParents.map(p => ({
                    value: p.id,
                    label: p.name,
                  })),
                ]}
                value={formData.parentId ?? 'none'}
                onChange={(value: string | number) => {
                  setFormData({
                    ...formData,
                    imageUrl: value === 'none' ? formData.imageUrl : null,
                    parentId: value === 'none' ? null : Number(value),
                  });
                }}
              />
              {!isRootCategory ? (
                <p className="text-muted-foreground text-xs">
                  Subcategories do not use images. Any selected image will be removed.
                </p>
              ) : null}
            </div>

            <div className="space-y-2">
              <Label htmlFor="description">Description</Label>
              <Textarea
                id="description"
                placeholder="Optional description of the category..."
                value={formData.description}
                onChange={e => setFormData({ ...formData, description: e.target.value })}
                className="resize-none"
                rows={3}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="status">Status*</Label>
              <Select
                value={formData.status}
                onValueChange={value =>
                  setFormData({ ...formData, status: value as 'active' | 'inactive' })
                }
              >
                <SelectTrigger id="status">
                  <SelectValue placeholder="Select status" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="active">Active</SelectItem>
                  <SelectItem value="inactive">Inactive</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
              disabled={isLoading}
            >
              Cancel
            </Button>
            <Button
              type="submit"
              variant="solid"
              isLoading={isLoading}
              disabled={isLoading || (isEdit && !isDirty)}
            >
              {isEdit ? 'Update Category' : 'Add Category'}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
