CREATE TABLE `orders` (
  `id` bigint unsigned AUTO_INCREMENT PRIMARY KEY,
  `orderNumber` varchar(50) NOT NULL,
  `userId` bigint unsigned NOT NULL,
  `status` enum('pending_confirmation','confirmed','processing','shipped','delivered','cancelled') NOT NULL DEFAULT 'pending_confirmation',
  `paymentMethod` varchar(50) NOT NULL,
  `paymentStatus` enum('unpaid','pending','paid','failed','cancelled','refunded','partially_refunded') NOT NULL DEFAULT 'unpaid',
  `paymentProvider` varchar(100),
  `paymentReference` varchar(255),
  `currency` char(3) NOT NULL,
  `subtotal` decimal(15,2) NOT NULL DEFAULT 0.00,
  `discountTotal` decimal(15,2) NOT NULL DEFAULT 0.00,
  `shippingTotal` decimal(15,2) NOT NULL DEFAULT 0.00,
  `taxTotal` decimal(15,2) NOT NULL DEFAULT 0.00,
  `grandTotal` decimal(15,2) NOT NULL DEFAULT 0.00,
  `shippingMethodCode` varchar(100),
  `couponCode` varchar(100),
  `notes` text,
  `shippingFullName` varchar(255) NOT NULL,
  `shippingPhone` varchar(50) NOT NULL,
  `shippingEmail` varchar(255),
  `shippingCountry` varchar(100) NOT NULL,
  `shippingState` varchar(100) NOT NULL,
  `shippingCity` varchar(100) NOT NULL,
  `shippingAddressLine1` varchar(255) NOT NULL,
  `shippingAddressLine2` varchar(255),
  `shippingPostalCode` varchar(50),
  `placedAt` datetime NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY `uniqOrderNumber` (`orderNumber`),
  KEY `idxOrdersUserCreatedAt` (`userId`, `createdAt`),
  KEY `idxOrdersStatusCreatedAt` (`status`, `createdAt`),
  KEY `idxOrdersPlacedAt` (`placedAt`),
  CONSTRAINT `fkOrdersUser` FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE `orderitems` (
  `id` bigint unsigned AUTO_INCREMENT PRIMARY KEY,
  `orderId` bigint unsigned NOT NULL,
  `productId` bigint unsigned NOT NULL,
  `productVariantId` bigint unsigned NOT NULL,
  `sku` varchar(100),
  `productName` varchar(255) NOT NULL,
  `variantName` varchar(255),
  `imageSrc` varchar(1024),
  `unitPrice` decimal(15,2) NOT NULL,
  `quantity` int NOT NULL,
  `lineTotal` decimal(15,2) NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY `idxOrderItemsOrder` (`orderId`),
  KEY `idxOrderItemsVariant` (`productVariantId`),
  CONSTRAINT `fkOrderItemsOrder` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `fkOrderItemsProduct` FOREIGN KEY (`productId`) REFERENCES `products` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fkOrderItemsVariant` FOREIGN KEY (`productVariantId`) REFERENCES `productvariants` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE `orderstatushistory` (
  `id` bigint unsigned AUTO_INCREMENT PRIMARY KEY,
  `orderId` bigint unsigned NOT NULL,
  `fromStatus` varchar(50),
  `toStatus` varchar(50) NOT NULL,
  `reason` varchar(500),
  `actorUserId` bigint unsigned,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY `idxOrderStatusHistoryOrder` (`orderId`),
  KEY `idxOrderStatusHistoryCreatedAt` (`createdAt`),
  CONSTRAINT `fkOrderStatusHistoryOrder` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `fkOrderStatusHistoryActor` FOREIGN KEY (`actorUserId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE RESTRICT
);
