'use client';

import { useMemo, useState } from 'react';

import { Brand, useCreateBrand, useUpdateBrand } from '@/hooks/useBrandQueries';
import { Button } from '@/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/ui/dialog';
import { Input } from '@/ui/input';
import { Label } from '@/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/ui/select';
import { Textarea } from '@/ui/textarea';

type BrandDialogProps = {
  brand: Brand | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
};

const INITIAL_FORM = {
  name: '',
  slug: '',
  description: '',
  status: 'active' as 'active' | 'inactive',
};

export function BrandDialog({ brand, open, onOpenChange }: BrandDialogProps) {
  const isEdit = !!brand;
  const createMutation = useCreateBrand();
  const updateMutation = useUpdateBrand();

  const initialData = useMemo(
    () =>
      brand
        ? {
            name: brand.name,
            slug: brand.slug,
            description: brand.description || '',
            status: brand.status || 'active',
          }
        : INITIAL_FORM,
    [brand],
  );

  const [formData, setFormData] = useState(initialData);

  // Auto-generate slug from name (only if slug hasn't been manually edited)
  const handleNameChange = (name: string) => {
    const autoSlug = name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');

    setFormData(prev => {
      // Check if current slug was auto-generated from previous name
      const prevAutoSlug = prev.name
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-|-$/g, '');
      const isSlugAutoGenerated = prev.slug === prevAutoSlug || prev.slug === '';

      return {
        ...prev,
        name,
        slug: isSlugAutoGenerated ? autoSlug : prev.slug,
      };
    });
  };

  const isDirty = JSON.stringify(formData) !== JSON.stringify(initialData);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    try {
      if (isEdit && brand) {
        await updateMutation.mutateAsync({ id: brand.id, data: formData });
      } else {
        await createMutation.mutateAsync(formData);
      }
      onOpenChange(false);
    } catch {
      // Error handling is done in the hook
    }
  };

  const isLoading = createMutation.isPending || updateMutation.isPending;

  return (
    <Dialog
      open={open}
      onOpenChange={onOpenChange}
    >
      <DialogContent className="max-w-md">
        {/* Using a key ensures the form is fully reset when the brand changes.
           If brand is null (create mode), key is "create".
           If editing, key uses the brand ID.
        */}
        <form onSubmit={handleSubmit}>
          <DialogHeader>
            <DialogTitle>{isEdit ? 'Edit Brand' : 'Add New Brand'}</DialogTitle>
            <DialogDescription>
              {isEdit ? 'Update brand details below.' : 'Add a new brand to the system.'}
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="name">Brand Name*</Label>
              <Input
                id="name"
                placeholder="e.g. BMW"
                value={formData.name}
                onChange={e => handleNameChange(e.target.value)}
                required
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="slug">Slug*</Label>
              <Input
                id="slug"
                placeholder="e.g. bmw"
                value={formData.slug}
                onChange={e => {
                  const sanitized = e.target.value
                    .toLowerCase()
                    .replace(/\s+/g, '-')
                    .replace(/[^a-z0-9-]/g, '');
                  setFormData({ ...formData, slug: sanitized });
                }}
                required
              />
              <p className="text-muted-foreground text-xs">
                URL-friendly identifier (lowercase, no spaces)
              </p>
            </div>

            <div className="space-y-2">
              <Label htmlFor="description">Description</Label>
              <Textarea
                id="description"
                placeholder="Optional description of the brand..."
                value={formData.description}
                onChange={e => setFormData({ ...formData, description: e.target.value })}
                className="resize-none"
                rows={3}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="status">Status*</Label>
              <Select
                value={formData.status}
                onValueChange={value =>
                  setFormData({ ...formData, status: value as 'active' | 'inactive' })
                }
              >
                <SelectTrigger id="status">
                  <SelectValue placeholder="Select status" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="active">Active</SelectItem>
                  <SelectItem value="inactive">Inactive</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
              disabled={isLoading}
            >
              Cancel
            </Button>
            <Button
              type="submit"
              variant="solid"
              isLoading={isLoading}
              disabled={isLoading || (isEdit && !isDirty)}
            >
              {isEdit ? 'Update Brand' : 'Add Brand'}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
